import pandas as pd
df = pd.read_csv('data/startup_funding.csv')
print(df.head())
print("\nNull values in each rows and columns:")
print(df.isnull().sum())
print("\nduplicated values in each rows and columns:")
print(df.duplicated().sum())
print("data info",df.info())
print(df.describe())
print(list(df.columns))
print(df.dtypes)
print("investment amount statistics analytics:")
print(df['InvestmentAmount_USD'].describe())
df.to_csv('data/cleaned_startup_funding.csv', index=False)
print("cleaned dataset successfully saved")
